Adds invisible character detection logic and updates tests
keep-starknet-strange/cairo-lint pull request #121
Opened 2024-09-26 03:57 UTC by CristopherAguilar10

This PR will add in invisible character detection functionality in code-expressions to the Cairo plugin.

**Invisible Character and Whitespaces detection:**

- The Function `check_invisible_characters` is implemented and performs the following checks in the `Expr`: 
- Whitespaces: a warning of (`Severity::Warning`) if present.
- Invisible characters: error (`Severity::Error`) on C-style  string literals like` \u{200B}`, `\u{00AD}`, `\u{200C}`, `\u{200D}`, `\u{202C}`, `\u{FEFF}`.

**Motivation:**

- The invisible kind of characters, like `zero-width space`, can create bugs that are impossible to trace in the code. This change enables the detection of such unwanted characters and possibly a warning/blocking their usage in code to guarantee the quality of source code.

**Diagnostic Messages Add following two diagnostic messages:**

- "Whitespace detected.": Whenever whitespace is detected.
- "Invisible character detected.": When invisible characters are detected.

2024-09-30 09:30 UTC, 0xLucqs commented
check the test file it's full of unrelated diagnostics

2024-10-01 17:52 UTC, CristopherAguilar10 commented
@0xLucqs, could you check the changes, thanks  🚀

2024-10-02 10:03 UTC, 0xLucqs requested changes

2024-10-02 10:03 UTC, 0xLucqs commented on crates/cairo-lint-core/src/plugin.rs
> +                    }
you should check the whole file not just inline macros

2024-10-02 10:03 UTC, 0xLucqs commented on crates/cairo-lint-core/tests/test_files/invisible_characters/invisible_characters
> +//! > cairo_code
remove every diagnostic that's not related to this lint

2024-10-07 08:10 UTC, closed without merging