Feat: add comparison_to_empty
keep-starknet-strange/cairo-lint pull request #130
Opened 2024-09-30 19:31 UTC by Benjtalkshow

closes #74 

This is a draft PR 
## Implementation
Checks for comparing to an empty slice such as [], and suggests using .is_empty() where applicable.

2024-10-01 07:41 UTC, 0xLucqs requested changes

2024-10-01 07:41 UTC, 0xLucqs commented on crates/cairo-lint-core/src/lints/comparison_to_empty.rs
> +}
don't need this function, directly create the diagnostic

2024-10-01 07:41 UTC, 0xLucqs commented on crates/cairo-lint-core/src/lints/mod.rs
> +// pub mod comparison_to_empty;
uncomment that

2024-10-01 08:48 UTC, Benjtalkshow commented
Alright @0xLucqs

2024-10-01 09:15 UTC, Benjtalkshow commented
@0xLucqs  i have made the requested changes

2024-10-01 09:20 UTC, 0xLucqs commented
fix clippy and don't forget to format

2024-10-01 09:23 UTC, Benjtalkshow commented
> fix clippy and don't forget to format

ok

2024-10-01 11:42 UTC, 0xLucqs commented
you need to add the tests to the test file similarly to how it's done with others

2024-10-03 23:48 UTC, Benjtalkshow commented
> fix the tests, remove the useless added file and restore the cargo.lock plz

alright

2024-10-07 08:14 UTC, closed without merging