feat : int operation one
keep-starknet-strange/cairo-lint pull request #144
Opened 2024-10-15 10:39 UTC by chachaleo

Resolves : #79 

Implementation of lint for unnecessary operations in integer comparison :

 * x >= y + 1
 * x - 1 >= y
 * x + 1 <= y
 * x <= y - 1

2024-10-15 21:48 UTC, 0xLucqs requested changes

2024-10-15 21:48 UTC, 0xLucqs commented on crates/cairo-lint-core/src/lints/int_op_one.rs
> +pub const ALLOWED: [&str; 1] = [LINT_NAME];
ajoute ca dans le `declared_allows` dans `plugin.rs`

2024-10-15 21:48 UTC, 0xLucqs commented on crates/cairo-lint-core/src/lints/int_op_one.rs
> +            && !expr_func.function.full_name(db).contains("PartialOrd::le"))
declare une variable `let full_name = expr_func.function.full_name...` et check bien que le `PartialOrd` est bien `core::PartialOrd`

2024-10-15 21:48 UTC, 0xLucqs commented on crates/cairo-lint-core/src/lints/int_op_one.rs
> +    };
chain les if avec des `&&`

2024-10-15 21:48 UTC, 0xLucqs commented on crates/cairo-lint-core/tests/test_files/int_op_one/int_op_one
> +//! > int ge plus one
rajoute un test ou tu allow le lint

2024-10-15 21:48 UTC, 0xLucqs commented on crates/cairo-lint-core/src/lints/int_op_one.rs
> +    true
```suggestion
    if let ExprFunctionCallArg::Value(val_expr) = arg {
        matches!(arenas.exprs[*val_expr], Expr::Var(_))
    } else {
        false
    }
```

2024-10-15 21:48 UTC, 0xLucqs commented on crates/cairo-lint-core/src/lints/int_op_one.rs
> +    if !func_call.function.full_name(db).contains("core::integer::")
crée une variable avec le nom de la fonction

2024-10-16 02:09 UTC, chachaleo commented on crates/cairo-lint-core/src/lints/int_op_one.rs
> +            && !expr_func.function.full_name(db).contains("PartialOrd::le"))
Le full name pour les u32 c'est core::integer::U32PartialOrd::ge donc j'ai mis les deux condition core::integer et PartialOrd::ge (ou ::le)

2024-10-16 12:29 UTC, 0xLucqs commented on crates/cairo-lint-core/src/lints/int_op_one.rs
> +        diagnostics.push(PluginDiagnostic {
tu devrais return après un diagnostic pour éviter d'exécuter le reste de la fonction pour rien non ?

2024-10-18 08:43 UTC, 0xLucqs approved these changes

2024-10-18 08:45 UTC, 0xLucqs commented on crates/cairo-lint-core/src/lints/int_op_one.rs
> +            && !expr_func.function.full_name(db).contains("PartialOrd::le"))
[cette fonction](https://github.com/keep-starknet-strange/cairo-lint/blob/9edc8f0d6e8b0e4ce4e5a0cfc1d81d093f3a2566/crates/cairo-lint-core/src/lints/mod.rs#L43-L56) te récupère le trait duquel ta fonctione est issuedonc ca t'affichera `core::PartialOrd` ou `core::traits::PartialOrd` je sais plus mais tu vois l'idée

2024-10-18 08:46 UTC, merged