feat: Add impossible_comparisons #76
keep-starknet-strange/cairo-lint pull request #95
Opened 2024-09-21 01:01 UTC by MariangelaNM

**Issue**
[76](https://github.com/keep-starknet-strange/cairo-lint/issues/76)

**Description**
1.  Implement is_impossible_double_comparison.
2. Fix the current implementation.
3. Add and update tests.

2024-09-25 15:28 UTC, MariangelaNM commented
@0xLucqs

2024-09-25 15:30 UTC, 0xLucqs requested changes

2024-09-25 15:30 UTC, 0xLucqs commented on crates/cairo-lint-core/src/lints/double_comparison.rs
> +    "The condition contains contradictory comparisons, meaning no value can satisfy both conditions at once.";
this is redundant with `pub const CONTRADICTORY_COMPARISON: &str = "This double comparison is contradictory and always false.";`

2024-09-25 15:30 UTC, 0xLucqs commented on crates/cairo-lint-core/src/lints/double_comparison.rs
> +                ));
this is redundant with `is_contradictory_double_comparison` can you just add your code to this function ? or even better move this into a new lint

2024-09-25 15:30 UTC, 0xLucqs commented on crates/cairo-lint-core/tests/test_files/double_comparison/double_comparison
> +
add 1 test for every impossible case

2024-09-26 00:13 UTC, MariangelaNM commented
@0xLucqs

2024-09-26 19:24 UTC, MariangelaNM commented
@0xLucqs , I joined the two logics in is_impossible_double_comparison and added two more examples.

2024-09-30 09:18 UTC, 0xLucqs commented on crates/cairo-lint-core/src/lints/double_comparison.rs
> +    }
I don't understand what you're doing here

2024-09-30 22:07 UTC, MariangelaNM commented
@0xLucqs ,I updated the initial function to include two additional cases: checking for `x > y && x >= y` and `x <= y && x > y`.

2024-10-02 09:53 UTC, 0xLucqs commented on crates/cairo-lint-core/src/lints/double_comparison.rs
> +            | (BinaryOperator::LE(_), BinaryOperator::AndAnd(_), BinaryOperator::GT(_))
these are not contradictory

2024-10-02 09:54 UTC, 0xLucqs commented on crates/cairo-lint-core/src/lints/double_comparison.rs
> +            | (BinaryOperator::LE(_), BinaryOperator::AndAnd(_), BinaryOperator::GT(_))
they're redundant

2024-10-02 17:19 UTC, MariangelaNM commented
@0xLucqs ,Based on your feedback, I adjusted the logic and placed it in `is_redundant_double_comparison`

2024-10-04 08:45 UTC, 0xLucqs approved these changes

2024-10-04 08:45 UTC, merged

2024-10-07 12:16 UTC, 0xLucqs commented
@all-contributors please add @MariangelaNM for code and tests